language: python
python:
- 2.7
before_install:
  - sudo apt-get -y install pelican
install:
  - ls
notifications:
  email:
    on_success: never
    on_failure: always
script: "./build.sh"
branches:
  only:
  - website-source
  except:
  - master  
