language: python
python:
- 2.7
install:
- pip install -r requirements.txt
notifications:
  email:
    on_success: never
    on_failure: always
script: "./build.sh"
branches:
  only:
  - website-source
  except:
  - master  
