---
name: CI

on:
  push:
    branches: ["website-source"]

jobs:
  publish:
    name: "Public blog"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2"

      - uses: "actions/setup-python@v2"
        with:
          python-version: 2.7
      
      - name: "Build and commit"
        run: |
          ./build.sh